version: "2"
services:
  node:
    image: "node:8.5.0"
    environment:
      - NODE_ENV=development
    volumes:
      - "./:/usr/src/app"
    ports:
      - 5000:5000
    working_dir: /usr/src/app
    command: yarn dev
    links: 
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
